# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Interface between R code and the Cox PH regression
#' \code{cox_ph_transition} Called directly from R, Defines the control variables and calls the regression function
#' @param Term_n Term numbers
#' @param tform subterm types
#'
#' @return LogLik_Cox_PH output : Log-likelihood of optimum, first derivative of log-likelihood, second derivative matrix, parameter list, standard deviation estimate, AIC, model information
cox_ph_transition <- function(Term_n, tform) {
    .Call(`_Colossus_cox_ph_transition`, Term_n, tform)
}

